# Generated by Django 4.2.5 on 2023-10-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_articulo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
