# Generated by Django 4.2.5 on 2023-10-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_articulo_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
