# Generated by Django 4.2.5 on 2023-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
